version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "nest"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - app
networks:
  app: